version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres_container:5432/analytics_dashboard
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analytics_dashboard
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
